# -*- mode: ruby -*-
# vi: set ft=ruby :

# Author Francisco Philip

Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/trusty64"

    config.vm.hostname = "hadoop"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.name = "hadoop"
    end


    config.vm.network "private_network", ip: "192.168.33.20"

    if Vagrant.has_plugin?("vagrant-proxyconf")
        config.proxy.no_proxy = "localhost,127.0.0.1"
    end

    config.vm.network "forwarded_port", guest: 22, host: 2022
    config.vm.network "forwarded_port", guest: 50070, host: 50070
    config.vm.network "forwarded_port", guest: 50075, host: 50075
    config.vm.network "forwarded_port", guest: 8088, host: 8088
    config.vm.network "forwarded_port", guest: 8042, host: 8042
    config.vm.network "forwarded_port", guest: 19888, host: 19888


    config.vm.synced_folder "../../", "/home/vagrant/workspace/", id: "workspace", :mount_options => []

    config.vm.provision "file", source: "../resources", destination: "$HOME/install-resources"

    config.vm.provision :shell, inline: <<-SHELL

      sed -ie '/^XKBLAYOUT=/s/".*"/"es"/' /etc/default/keyboard && udevadm trigger --subsystem-match=input --action=change
      dpkg-reconfigure keyboard-configuration -f noninteractive


      add-apt-repository ppa:openjdk-r/ppa -y
      apt-get update


      echo "\n"
      echo "\n"
      echo "---------- Installing Java 8 ------------\n"
      apt-get -y install apache2 openjdk-8-jdk
      rm -rf /var/lib/apt/lists/*

    SHELL

end


