# -*- mode: ruby -*-
# vi: set ft=ruby :

# Author Francisco Philip

Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/trusty64"

    config.vm.hostname = "hadoop"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.name = "hadoop"
    end


    config.vm.network "private_network", ip: "192.168.33.20"

    if Vagrant.has_plugin?("vagrant-proxyconf")
        config.proxy.no_proxy = "localhost,127.0.0.1"
    end

    config.vm.network "forwarded_port", guest: 22, host: 2022
    config.vm.network "forwarded_port", guest: 50070, host: 50070
    config.vm.network "forwarded_port", guest: 50075, host: 50075
    config.vm.network "forwarded_port", guest: 8020, host: 8020
    config.vm.network "forwarded_port", guest: 8088, host: 8088
    config.vm.network "forwarded_port", guest: 8042, host: 8042
    config.vm.network "forwarded_port", guest: 19888, host: 19888


    config.vm.synced_folder "../../../", "/sources/", id: "sources", :mount_options => []

    config.vm.provision "file", source: "../resources", destination: "/home/vagrant/install/"
    config.vm.provision "file", source: "../scripts/", destination: "/home/vagrant/install/"

    config.vm.provision :shell, inline: <<-SHELL

      sed -ie '/^XKBLAYOUT=/s/".*"/"es"/' /etc/default/keyboard && udevadm trigger --subsystem-match=input --action=change
      dpkg-reconfigure keyboard-configuration -f noninteractive


      add-apt-repository ppa:openjdk-r/ppa -y
      apt-get update
      apt-get -y install apache2 openjdk-8-jdk
      rm -rf /var/lib/apt/lists/*

      export HADOOP_VERSION=2.9.1
      export HADOOP_HOME=/usr/local/hadoop
      export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))

      bash /home/vagrant/install/scripts/setup.sh

      echo "export HADOOP_VERSION='${HADOOP_VERSION}'" >> /etc/profile.d/HADOOP_VERSION.sh
      echo "export HADOOP_HOME='${HADOOP_HOME}'" >> /etc/profile.d/HADOOP_HOME.sh
      echo "export HADOOP_CONF_DIR='${HADOOP_HOME}/etc/hadoop'" >> /etc/profile.d/HADOOP_CONF_DIR.sh
      echo "export HADOOP_MAPRED_HOME='${HADOOP_HOME}'" >> /etc/profile.d/HADOOP_MAPRED_HOME.sh
      echo "export HADOOP_COMMON_HOME='${HADOOP_HOME}'" >> /etc/profile.d/HADOOP_COMMON_HOME.sh
      echo "export HADOOP_HDFS_HOME='${HADOOP_HOME}'" >> /etc/profile.d/HADOOP_HDFS_HOME.sh
      echo "export YARN_HOME='${HADOOP_HOME}'" >> /etc/profile.d/YARN_HOME.sh
      echo "export JAVA_HOME='${JAVA_HOME}'" >> /etc/profile.d/JAVA_HOME.sh
      

      mkdir -p  /home/hadoop/
      mv /home/vagrant/install/scripts/user-config.sh /home/hadoop/

    SHELL

end


