# -*- mode: ruby -*-
# vi: set ft=ruby :

# Author Francisco Philip

Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/trusty64"

    config.vm.hostname = "kafka"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.name = "kafka"

    end


  config.vm.network "private_network", ip: "192.168.33.41"

    if Vagrant.has_plugin?("vagrant-proxyconf")
        config.proxy.no_proxy = "localhost,127.0.0.1"
    end

    config.vm.network "forwarded_port", guest: 22, host: 4122


    config.vm.synced_folder "../../../", "/sources/", id: "sources", :mount_options => []

    config.vm.provision :shell, inline: <<-SHELL

      sed -ie '/^XKBLAYOUT=/s/".*"/"es"/' /etc/default/keyboard && udevadm trigger --subsystem-match=input --action=change
      dpkg-reconfigure keyboard-configuration -f noninteractive

      sudo apt-get install apt-transport-https ca-certificates



      SHELL

end


